### ISSUE TITLE
Select component from chakra should not use variant = "mini"

### ISSUE THREAD

**Issue by matdexir** [horizon-ui/horizon-ui-chakra-nextjs#1]
Hi,
I like your template very much! It looks very nice!
However, I was looking around and it seems using the "mini" variant from the Select component leads to the options being "minified"(i.e invisible) as well.

![2023-02-11_00-34](https://user-images.githubusercontent.com/58453130/218145566-51ea0b5d-f09a-4e6e-95bb-434ce2b0afa8.png)

**Comment by simmmpleweb** [comment]
Hello, @matdexir ! Thanks for supporting Horizon! We just solved the issue!
