### ISSUE TITLE
Responsiveness broken on the Sign-in page

### ISSUE THREAD

**Issue by willvlad** [horizon-ui/horizon-ui-chakra-nextjs#2]
![image](https://user-images.githubusercontent.com/8473897/224808560-78fe8a4e-84da-498d-b505-d0c554471f50.png)

As you can see, the button goes beyond the visible screen on smaller screens

**Comment by simmmpleweb** [comment]
Hello, @willvlad ! Thanks for supporting Horizon! Can you please share with me the viewport and browser you got this error on?
Regards, Vlad.

**Comment by willvlad** [comment]
Hi Vlad, that's just in the Chrome browser simply as you shrink the viewport border. I fixed it, but can't remember how now. I just compared your typescript version with your nextjs one and there was a css setting on the wrapping Flex that was different between the two. When i removed it, it worked fine. 

By the way, I might need some minor paid work to be done based on your template. Who is the best person to discuss it with?

**Comment by simmmpleweb** [comment]
I fixed the problem in the code source as well! As for the work based on our template, we do not do paid services based on Horizon, but, you can join [our Discord Community](https://discord.gg/f6tEKFBd4m), and ask the people that already use Horizon for their projects if they can help you with this! I hope this helps!
