### ISSUE TITLE
Support for NextJS v.13

### ISSUE THREAD

**Issue by mfentross** [horizon-ui/horizon-ui-chakra-nextjs#3]
As of now the project only supports v12 of NextJS and thus does not include the new app directory. Will there ever be an upgrade?

**Comment by simmmpleweb** [comment]
Hello, @mfentross! Thanks for supporting Horizon! For the moment, just the PRO version of Horizon comes with the NextJS v13 update, including the layouts feature, the app directory, and so on. We are working on upgrading this free version as well, so stay tuned! Hope this helps! 😁

Regards, Fredy.
